#!/bin/bash

script_name=$(basename "$0")

for file in *
do
    if [ ! -f "$file" ]; then
        continue
    fi

    if [ "$file" = "$script_name" ]; then
        continue
    fi

    if [[ "$file" == *.* ]]; then
        ext="${file##*.}"

        mkdir -p "$ext"

        mv "$file" "$ext/"
    fi
done

